# Generated by Django 3.2.18 on 2023-03-23 22:05

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Stocklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_list', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Storagespace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('temp', models.IntegerField(default=21)),
                ('stocklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage_space', to='stocklist.stocklist')),
            ],
        ),
        migrations.CreateModel(
            name='Stockitem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('remarks', models.TextField()),
                ('product_image', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image')),
                ('min_temp', models.IntegerField(default=-30)),
                ('max_temp', models.IntegerField(default=30)),
                ('quantity', models.IntegerField(default=1)),
                ('uom', models.CharField(choices=[('PC', 'pc'), ('L', 'L'), ('KG', 'kg'), ('BOTTLE', 'bottle'), ('CUP', 'cup'), ('PACK', 'pack')], default='PC', max_length=50)),
                ('storage', models.ManyToManyField(to='stocklist.Storagespace')),
            ],
        ),
    ]
