# Generated by Django 3.2.18 on 2023-03-24 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocklist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockitem',
            name='remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='stocklist',
            name='name',
            field=models.CharField(default='Your Stock List', max_length=150),
        ),
    ]
