# Generated by Django 3.2.18 on 2023-03-24 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocklist', '0002_auto_20230324_0808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockitem',
            name='expiry_date',
            field=models.DateField(null=True),
        ),
    ]
