# Generated by Django 3.2.18 on 2023-03-24 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocklist', '0003_alter_stockitem_expiry_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockitem',
            name='storage',
        ),
        migrations.AddField(
            model_name='stockitem',
            name='storage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_item', to='stocklist.storagespace'),
        ),
    ]
