# Generated by Django 3.2.18 on 2023-04-01 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocklist', '0005_auto_20230325_1917'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stocklist',
            options={'ordering': ['-created_on']},
        ),
    ]
