# Generated by Django 3.2.18 on 2023-04-02 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocklist', '0006_alter_stocklist_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockitem',
            old_name='name',
            new_name='item_name',
        ),
        migrations.RenameField(
            model_name='storagespace',
            old_name='name',
            new_name='str_name',
        ),
    ]
