# Generated by Django 3.2.18 on 2023-04-02 14:58

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocklist', '0008_rename_str_name_storagespace_storage_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocklist',
            name='list_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
