# Generated by Django 3.2.18 on 2023-04-04 20:57

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocklist', '0011_auto_20230404_2051'),
    ]

    operations = [
        migrations.CreateModel(
            name='Storagespace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage_name', models.CharField(max_length=150, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('temp', models.IntegerField(default=21)),
                ('stocklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage_space', to='stocklist.stocklist')),
            ],
        ),
        migrations.CreateModel(
            name='Stockitem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('expiry_date', models.DateField(null=True)),
                ('remarks', models.TextField(blank=True)),
                ('product_image', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image')),
                ('min_temp', models.IntegerField(default=-30)),
                ('max_temp', models.IntegerField(default=30)),
                ('quantity', models.IntegerField(default=1)),
                ('item_updated_on', models.DateTimeField(auto_now=True, null=True)),
                ('uom', models.CharField(choices=[('PC', 'pc'), ('L', 'L'), ('KG', 'kg'), ('BOTTLE', 'bottle'), ('CUP', 'cup'), ('PACK', 'pack')], default='PC', max_length=50)),
                ('storage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_item', to='stocklist.storagespace')),
            ],
        ),
    ]
