# Generated by Django 3.2.18 on 2023-04-04 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocklist', '0012_stockitem_storagespace'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockitem',
            name='slug',
        ),
    ]
