# Generated by Django 3.2.18 on 2023-04-05 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocklist', '0013_remove_stockitem_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockitem',
            name='product_image',
        ),
    ]
