# Generated by Django 3.2.18 on 2023-04-05 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocklist', '0014_remove_stockitem_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockitem',
            name='item_updated_on',
        ),
        migrations.AddField(
            model_name='storagespace',
            name='storage_updated_on',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
