# Generated by Django 3.2.18 on 2023-04-14 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocklist', '0015_auto_20230405_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocklist',
            name='stocklist_slug',
            field=models.SlugField(default='test', max_length=200),
        ),
    ]
