# Generated by Django 3.2.18 on 2023-04-14 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocklist', '0016_stocklist_stocklist_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocklist',
            name='stocklist_slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
    ]
