# Generated by Django 3.2.18 on 2023-04-18 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocklist', '0018_rename_stocklist_slug_stocklist_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocklist',
            name='slug',
            field=models.SlugField(max_length=200),
        ),
    ]
