# Generated by Django 3.2.18 on 2023-04-18 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocklist', '0019_alter_stocklist_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocklist',
            name='name',
            field=models.CharField(default='Your Stock List', max_length=150, unique=True),
        ),
    ]
