# Generated by Django 3.2.18 on 2023-04-18 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocklist', '0020_alter_stocklist_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocklist',
            name='name',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
