# Generated by Django 3.2.18 on 2023-04-20 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocklist', '0021_alter_stocklist_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storagespace',
            name='stocklist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='storage_space', to='stocklist.stocklist'),
        ),
    ]
