# Generated by Django 3.2.18 on 2023-04-20 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocklist', '0022_alter_storagespace_stocklist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storagespace',
            name='storage_name',
            field=models.CharField(max_length=150),
        ),
    ]
