# Generated by Django 3.2.18 on 2023-04-22 15:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stocklist', '0024_stocklist_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stocklist',
            name='created_by',
        ),
        migrations.AlterField(
            model_name='stocklist',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stock_list', to=settings.AUTH_USER_MODEL),
        ),
    ]
