# Generated by Django 3.2.18 on 2023-04-22 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocklist', '0026_alter_stocklist_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocklist',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='storagespace',
            unique_together={('stocklist', 'storage_name')},
        ),
    ]
