# Generated by Django 3.2.18 on 2023-04-22 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocklist', '0027_auto_20230422_1554'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='storagespace',
            unique_together=set(),
        ),
    ]
