# Generated by Django 3.2.18 on 2023-04-23 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocklist', '0031_alter_storagespace_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stockitem',
            unique_together={('storage', 'item_name')},
        ),
    ]
