# Generated by Django 3.2.18 on 2023-04-27 07:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stocklist', '0033_alter_stockitem_item_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockitem',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
