# Generated by Django 3.2.18 on 2023-04-29 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocklist', '0034_stockitem_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storagespace',
            name='storage_updated_on',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
