# Generated by Django 3.2.18 on 2023-05-05 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocklist', '0035_alter_storagespace_storage_updated_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocklist',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
