# Generated by Django 3.2.18 on 2023-05-05 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocklist', '0036_alter_stocklist_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storagespace',
            name='storage_name',
            field=models.CharField(max_length=20),
        ),
    ]
