# Generated by Django 3.2.18 on 2023-05-18 20:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocklist', '0037_alter_storagespace_storage_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockitem',
            name='max_temp',
            field=models.IntegerField(default=30, validators=[django.core.validators.MaxValueValidator(30), django.core.validators.MinValueValidator(-30)]),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='min_temp',
            field=models.IntegerField(default=-30, validators=[django.core.validators.MaxValueValidator(30), django.core.validators.MinValueValidator(-30)]),
        ),
    ]
